### PR TITLE
Fixed ChatPrefix/ChatSuffix

### PR DESCRIPTION
**Pull request by AcaiBerii**
Merged ChatPrefix and ChatSuffix into one module called "ChatModifications". Also used switch and case instead of if and else because I felt like it.

Also removed stupidity.

### CODE REVIEW

**Comment by Gav06** [comment]
what

**Comment by Gav06** [comment]
i mean bypass mode on flight probably wouldnt even work anyways
but whatever

**Review by Gav06 — APPROVED** [review]
mk

**Comment by AcaiBerii** [comment]
someone else changed it to bypass mode not my problem LOL!

**Comment by AcaiBerii** [comment]
gav https://acaiberii.is-a.dev/gavhack-web/ pls website ily gav

**Comment by Gav06** [comment]
gavsense
:OOO

**Comment by AcaiBerii** [comment]
am still waiting for the fonts to load LOL SRY ILY GAV

**Comment by AcaiBerii** [comment]
IT WORKS NOW ILY GAV

**Comment by Gav06** [comment]
i will merge after i resolve all the conflicts later

**Comment by Gav06** [comment]
we dont need disabler and stuff since its a 1.12.2 client
and also idk how to use git and fix the conflicts

**Pull request closed without merging**
