### PR TITLE
Another one!

### PR DESCRIPTION
**Pull request by AcaiBerii**
- Add disabler
- Modify FootXP
- Add LoginBypass (rede momento)
- Remove Wrapper and WrapperUtil
- Do the funny

### CODE REVIEW

**Comment by Gav06** [comment]
i dont like wrapper
static evil

**Comment by Gav06** [comment]
still gud ig

**Comment by AcaiBerii** [comment]
lol i guess its bad but it works

**Comment by Gav06** [comment]
can you just remove the wrapper & wrapperutil, and just use the minecraft methods normally? seems kinda bloaty imo

**Comment by yagel15637** [comment]
> lol i guess its bad but it works

bad mindset, in general and specifically in open sourced projects with no release date planned

**Comment by Gav06** [comment]
image

hmm

**Comment by AcaiBerii** [comment]
Try seeing again? Everything worked with me, I'll fix it rn.

**Comment by AcaiBerii** [comment]
Build worked!

**Review by Gav06 — COMMENTED** [review]
i

**Pull request merged**
